//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiketreservasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class pajak_bandara
    {
        public int id_bandara { get; set; }
        public string nm_bandara { get; set; }
        public decimal pajak { get; set; }
    }
}
